ci:
    build: .buildkite/
    working_dir: /go/src/github.com/99designs/ecs-cli
    volumes:
        - .:/go/src/github.com/99designs/ecs-cli
    environment:
        - AWS_ACCESS_KEY_ID
        - AWS_REGION
        - AWS_DEFAULT_REGION
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
