steps:
  -
    type: "script"
    name: "Test go"
    command: ".buildkite/test.sh"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: "ci"
    agent_query_rules:
      - "queue=elastic-v2"
    # Its not safe to run these in parallel, they would all create/delete the same resources
    concurrency: 1
    concurrency_group: "ecs-cli-acceptance"