
Parameters:
  TaskDefinition:
    Type: String
    Description: The identifier of the ECS TaskDefinition to use

  ContainerPort:
    Type: Number
    Description: The port on the container and load balancer to open
    Default: 80

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: A security group for the ELB that has access to the ECS Cluster Instances

Outputs:
  ECSLoadBalancer:
    Value: $(ECSLoadBalancer)
  AppURL:
    Value: !Join ["", "http://", !GetAttr [ $(ECSLoadBalancer), "DNSName" ], ":",  $(ContainerPort)]

Resources:
  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
       GroupDescription : Security group for ELB in front of ECS
       VpcId : $(Vpc)
       SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: $(ContainerPort)
          ToPort: $(ContainerPort)
          CidrIp: 0.0.0.0/0

  ECSLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Subnets: $(Subnets)
      SecurityGroups: [ $(ELBSecurityGroup), $(ECSSecurityGroup) ]
      Listeners:
        - LoadBalancerPort: $(ContainerPort)
          InstancePort: $(ContainerPort)
          Protocol: HTTP
      HealthCheck:
        Target: HTTP:$(ContainerPort)/
        HealthyThreshold: 2
        UnhealthyThreshold: 10
        Interval: 30
        Timeout: 5
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 60

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: $(ECSCluster)
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: $(ContainerName)
          ContainerPort: 80
          LoadBalancerName: $(ECSLoadBalancer)
      Role: $(ECSServiceRole)
      TaskDefinition: $(TaskDefinition)

  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ecs-service
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:Describe*
                  - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
                  - elasticloadbalancing:RegisterInstancesWithLoadBalancer
                  - ec2:Describe*
                  - ec2:AuthorizeSecurityGroupIngress
                Resource: "*"